### ISSUE TITLE
Oraclepii website doesn't load

### ISSUE THREAD

**Issue by imahbub** [The-Penguins-Club/bd-startups#15]
It seems there is an issue with the web address included in this list for **ওরাকলপাই ইনোভেশন**. When you visit the URL, **it simply does not load**. Check this image 

![image](https://user-images.githubusercontent.com/63340482/145793995-7f098256-57da-4bd7-84c3-bb9a303ef574.png)

**Comment by uthsobcb** [comment]
I talked with founder but seems disappointed and i guess they wouldn't start again so you can remove this site from list.

**Comment by fazlerabbi37** [comment]
as it's assigned to you, make a PR when you are free. :smile_cat:

**Comment by fazlerabbi37** [comment]
@uthsobcb, instead of removing, comment it out. I would like to get them back when they are up 😊

obviously, send the PR when you are **free**!

**Comment by uthsobcb** [comment]
Check the last pr.

**Comment by uthsobcb** [comment]
Please remove OraclePii from the list.
